### ISSUE TITLE
AWS missing permissions

### ISSUE THREAD

**Issue by tomdeakin** [clusterinthecloud/docs#14]
When running `finish` on the configured AWS node, I had this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/update_config", line 89, in <module>
    node_config = "\n".join(get_node_configs(get_limits(), get_shapes(), get_mgmt_info(), get_nodespace()))
  File "/usr/local/bin/update_config", line 25, in get_shapes
    return citc.utils.get_types_info()
  File "/opt/cloud_sdk/lib64/python3.8/site-packages/citc/utils.py", line 52, in get_types_info
    return aws.get_types_info(ec2)
  File "/opt/cloud_sdk/lib64/python3.8/site-packages/citc/aws.py", line 80, in get_types_info
    instances = {
  File "/opt/cloud_sdk/lib64/python3.8/site-packages/citc/aws.py", line 80, in <dictcomp>
    instances = {
  File "/opt/cloud_sdk/lib64/python3.8/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/opt/cloud_sdk/lib64/python3.8/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/opt/cloud_sdk/lib64/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/cloud_sdk/lib64/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnauthorizedOperation) when calling the DescribeInstanceTypes operation: You are not authorized to perform this operation.
```

I worked around this by adding the `DescribeInstanceTypes` permission to the `start_stop_nodes_artistic-fox` User and `describe_tags-artistic-fox` Policy using the AWS Console GUI website thing.

**Comment by tomdeakin** [comment]
This GitHub Issue was helpful: https://github.com/aws/aws-parallelcluster/issues/1912

**Comment by milliams** [comment]
It turns out I had this change sitting in my local copy but had not yet committed it yet. It is now there at clusterinthecloud/terraform@fa74386d.
